# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form2.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget2(object):
    def setupUi(self, Widget2):
        Widget2.setObjectName("Widget2")
        Widget2.resize(800, 600)
        self.tableWidget = QtWidgets.QTableWidget(Widget2)
        self.tableWidget.setGeometry(QtCore.QRect(120, 200, 521, 211))
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.add = QtWidgets.QPushButton(Widget2)
        self.add.setGeometry(QtCore.QRect(210, 430, 111, 41))
        self.add.setObjectName("add")
        self.izm = QtWidgets.QPushButton(Widget2)
        self.izm.setGeometry(QtCore.QRect(450, 430, 111, 41))
        self.izm.setObjectName("izm")
        self.exit = QtWidgets.QPushButton(Widget2)
        self.exit.setGeometry(QtCore.QRect(630, 530, 121, 41))
        self.exit.setStyleSheet("background-color: rgb(255, 143, 145);")
        self.exit.setObjectName("exit")
        self.lineEdit = QtWidgets.QLineEdit(Widget2)
        self.lineEdit.setGeometry(QtCore.QRect(120, 130, 231, 31))
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton_4 = QtWidgets.QPushButton(Widget2)
        self.pushButton_4.setGeometry(QtCore.QRect(430, 130, 121, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox = QtWidgets.QComboBox(Widget2)
        self.comboBox.setGeometry(QtCore.QRect(120, 50, 181, 31))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Widget2)
        QtCore.QMetaObject.connectSlotsByName(Widget2)

    def retranslateUi(self, Widget2):
        _translate = QtCore.QCoreApplication.translate
        Widget2.setWindowTitle(_translate("Widget2", "Widget2"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Widget2", "ФИО"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Widget2", "Должность"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Widget2", "Подразделение"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Widget2", "Помещение"))
        self.add.setText(_translate("Widget2", "Добавить"))
        self.izm.setText(_translate("Widget2", "Изменить"))
        self.exit.setText(_translate("Widget2", "Выход"))
        self.pushButton_4.setText(_translate("Widget2", "Найти"))
        self.comboBox.setItemText(0, _translate("Widget2", "Сотрудники"))
        self.comboBox.setItemText(1, _translate("Widget2", "История должностей"))
        self.comboBox.setItemText(2, _translate("Widget2", "Подразделения"))
        self.comboBox.setItemText(3, _translate("Widget2", "Помещения"))

