# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(800, 600)
        self.vxod = QtWidgets.QPushButton(Widget)
        self.vxod.setGeometry(QtCore.QRect(310, 350, 171, 31))
        self.vxod.setObjectName("vxod")
        self.reg = QtWidgets.QPushButton(Widget)
        self.reg.setGeometry(QtCore.QRect(310, 400, 171, 31))
        self.reg.setObjectName("reg")
        self.parol = QtWidgets.QLineEdit(Widget)
        self.parol.setGeometry(QtCore.QRect(310, 290, 171, 31))
        self.parol.setObjectName("parol")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(320, 260, 111, 20))
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(Widget)
        self.lineEdit_2.setGeometry(QtCore.QRect(310, 210, 171, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_2 = QtWidgets.QLabel(Widget)
        self.label_2.setGeometry(QtCore.QRect(320, 180, 111, 20))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.vxod.setText(_translate("Widget", "Войти"))
        self.reg.setText(_translate("Widget", "Зарегистрироваться"))
        self.label.setText(_translate("Widget", "Введте пароль"))
        self.label_2.setText(_translate("Widget", "Введите логин"))

